### ISSUE TITLE
Prettier config not consistent with studio policy

### ISSUE THREAD

**Issue by JaccoGoris** [bothrs/open-source#18]
the current prettier config is
```JSON
{
  "arrowParens": "always",
  "endOfLine": "lf",
  "printWidth": 80,
  "quoteProps": "consistent",
  "semi": false,
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false
}
```

while the agreed upon studio config is: 
(See notion: Engineering way of working)

```JSON
{
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "tabWidth": 2
}
```

**Comment by FabianMeul** [comment]
What exactly are the side effects you are experiencing?
The config defined here simply enforces defaults that are otherwise chosen by Prettier, and could vary depending on Prettier version. Note how some of those default values changed when Prettier v2 was released, which would result in different formatting.

- arrowParens: 
  - default: "always"
  - https://prettier.io/docs/en/options.html#arrow-function-parentheses
- endOfLine:
  - default: "lf"
  - https://prettier.io/docs/en/options.html#end-of-line
- printWidth:
  - default: 80
  - https://prettier.io/docs/en/options.html#print-width
- quoteProps:
  - default: "as-needed"
  - https://prettier.io/docs/en/options.html#quote-props
  - Here the config deviates from the Engineering config, but I think a case can be made for "consistent".
- useTabs:
  - default: false
  - https://prettier.io/docs/en/options.html#tabs

**Comment by JaccoGoris** [comment]
Most of the defined ones are default anyway, like`printwidth:80`, so defining them is not needed. (though the original example probably also redefines defaults, yes)

The main issue I see with quoteProps `consistent` is that you will have these two examples:
```
const headers1 = { Accept: '*/*'  }
const headers2 = { 'Accept': '*/*', 'Content-type':'application/json'}
```

Since `Accept` is styled differently in both cases, it's actually more consistent to use `as-needed` in this case because the rule is then very clear since it's just a javascript rule: if there's special characters in your key, it needs quotes.

`as-needed` makes sure there's as little characters and clutter as possible. it makes the code.. prettier (no pun intended) and thus more readable. (I hope you don't find JSON more readable than JS notation at least :D )

**Comment by FabianMeul** [comment]
Middle ground;

- Keep the "extended" configuration, to prevent Prettier changing the defaults on us.
- Change the quoteProps to `as-needed`

Agreed? 🤓

**Comment by JaccoGoris** [comment]
super on board with this!
